#!/usr/bin/env bash

out_folder='mathgames-sdk'

rm -rf $out_folder
mkdir $out_folder
mkdir -p $out_folder

cp -r mathgames-src $out_folder/
cp -r sample-game $out_folder/
cp -r sample-game-src $out_folder/

zip -qr ./release-${1}.zip $out_folder

rm -rf $out_folder
